server:
  port: 8089

spring:
  application:
    name: a2a-server

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    io.github.a2ap: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# A2A specific configuration
a2a:
  server:
    enabled: true
    id: "server-hello-world"
    name: "A2A Java Server"
    description: "A sample A2A agent implemented in Java"
    version: "1.0.0"
    url: "http://localhost:${server.port}/"
    provider:
      name: "A2A"
      url: "https://github.com/a2aproject/a2a-java"
    documentationUrl: "https://github.com/a2aproject/a2a-java"
    capabilities:
      streaming: true
      pushNotifications: false
      stateTransitionHistory: true
    supportsAuthenticatedExtendedCard: true
    defaultInputModes:
      - "text"
    defaultOutputModes:
      - "text"
    skills:
      - name: "hello-world"
        description: "A simple hello world skill"
        tags:
          - "greeting"
          - "basic"
        examples:
          - "Say hello to me"
          - "Greet me"
        inputModes:
          - "text"
        outputModes:
          - "text"
